[build]
  functions = ".netlify/functions"
  command = 'npm run build'
  publish = '.'

[functions]
  external_node_modules = ["express", "serverless-http", "dotenv"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/app/:splat"